services:
  accomodation_api:
    build:
      context: '.'
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - RedisUrl=host.docker.internal:6379
    restart: unless-stopped

   

   